# Generated by Django 3.2.16 on 2023-07-27 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20230727_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.IntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('mark_2', models.IntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('mark_3', models.IntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
